### ISSUE TITLE
Problems & Suggestions

### ISSUE THREAD

**Issue by toonme** [brunull/pace#2]
Hello,
I have installed Pace and i know it's actually in "early access".
The "Command Prompt" and "Take a Screenshot" doesn't work, just the file manager send packet.
When the Server is closed , the client shutting down as well with a "disconnect".
Suggestion : 
-And i also quickly seen a downloadfile and execute can you add it?
-Add a uninstall function (self-destruct).
-A shutdown/restart for the computer.

Thanks you & GL for your project.

**Comment by typetrait** [comment]
Hello and thank you for your interest in the project.
Pace is actually in an early development stage, rather than an early access stage, meaning many of its features are not implemented and it's definitely not production ready yet. All of these features you have suggested are planned and will, eventually, be added.
