### ISSUE TITLE
Fix this

### ISSUE THREAD

**Issue by Dontmindmes** [brunull/pace#6]
I was unable to add contributions but here this should help

 Net Serialize source straight into the source of the project. Why?

Your using a List instead of an array
you creates a list and immediately turns it into an array?

also copy the front buffer for screen capture
Your trying to make a a rat without dependent libraries but dont know that Fody.Weaver exists

also no attempt on hiding his traffic, it’s all open and clear

**Comment by typetrait** [comment]
Hello, thank you for your interest in Pace.
You seem to have asked many questions inside this one single issue, but I'll do my best to answer them as best as I can.

> I was unable to add contributions

Why exactly is that? in order to contribute you should fork and clone the repository, commit your local changes and push them to the remote repository you forked and then open a pull request describing the changes you've made to the code.

>Net Serialize source straight into the source of the project. Why?

Both the source code available on GitHub and the Nuget package haven't been updated since 2016.

>Your using a List instead of an array
you creates a list and immediately turns it into an array?

It would help if you could point where exactly that happens. This issue doesn't help much if you don't give me some details, so that I can find the problem and possibly fix it.

>also copy the front buffer for screen capture

Not sure on what you mean here. Are you suggesting I should only capture the active window or use a different approach for screen captures?

>Your trying to make a a rat without dependent libraries but dont know that Fody.Weaver exists

I'm not trying to make a rat without dependencies. I already have a few, like the Pace.Common and NetSerializer libraries, shared by both the client and server. Also, I do know that "Fody.Weaver" exists. I've used it in the past alongside "Costura" for merging resources into a single assembly. It's not here because I haven't implemented it yet, I'm a just a single person working on this project, during my free time. That's why I welcome contributions with an open heart. It isn't there yet but not because I  neglect it, but simply because I'm working on something else at the moment, and that would be the features(the file explorer more specifically).

>also no attempt on hiding his traffic, it’s all open and clear

I'm aware the traffic isn't hidden, I do plan on implementing that but again, as I mentioned on my previous answer, when I do have the time for it(or if someone wants to help).

Your concerns are valid, but they should be put into individual issues, so I(or the contributors) can track them better.

For now, I'm closing this issue. If you could please do as I mentioned and open individual, well described issues I'll be happy to tackle them as soon as I can. Thank you.
